version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run:
        name: install-yarn
        command: sudo npm install -g yarn
      - checkout